name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18.x
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: actions/checkout@v2
      - run: go install github.com/deepmap/oapi-codegen/cmd/oapi-codegen@v1.11.0
      - run: go generate ./...
      - run: go test ./...
      - run: go build
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.46
      - if: startsWith(github.ref, 'refs/tags/v')
        run: echo "$DOCKER_PASS" | docker login ghcr.io --username "$DOCKER_USER" --password-stdin
        env:
          DOCKER_USER: ${{ github.repository_owner }}
          DOCKER_PASS: ${{ secrets.GITHUB_TOKEN }}
      - if: startsWith(github.ref, 'refs/tags/v')
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --skip-validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
